alias ..="cd .."
alias ...="cd ../.."
alias mkdir="mkdir -p"
alias df="df -h"
alias du="du -h"
alias tmp="cd $(mktemp -d)"
alias path='echo -e ${PATH//:/\\n}'

alias gi="git init"
alias gs="git status"
alias gc="git commit"
alias gco="git checkout"
alias ga="git add"
alias gb="git branch"
alias gba="git branch --all"
alias gd="git difftool"
alias gds="git diff -w --staged"
alias grs="git restore --staged"
alias grd="git fetch origin && git rebase origin/master"
alias gp="git push -u origin"
alias grh="git reset --hard"
alias gst="git stash"
alias gstp="git stash pop"
alias gbl="git blame -w -C -C -C"
alias gf="git fetch --all --prune"
alias grm="git rebase origin/master"
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all"
